INSERT INTO fragebogen (fach, frage, antwort_1, antwort_2, antwort_3, antwort_4, richtige_antwort, author_id) VALUES
-- Fragen aus "Einfuehrung in das Internet of Things"
('Einfuehrung in das Internet of Things', 'Ordnen Sie die folgenden Begrifflichkeiten in der korrekten Reihenfolge der Entwicklung vom Web 1.0 - Web 4.0 zu.', 
'Semantisches Web, Wikis, Homepages, Vernetzung von Alltagsgegenstaenden', 
'Homepages, Wikis, Semantisches Web, Vernetzung von Alltagsgegenstaenden', 
'Wikis, Homepages, Semantisches Web, Vernetzung von Alltagsgegenstaenden', 
'Homepages, Wikis, Vernetzung von Alltagsgegenstaenden, Semantisches Web', 
2, 1),

('Einfuehrung in das Internet of Things', 'Die standardisierte Datenbankabfragesprache, um auf Daten in relationalen Datenbanken zugreifen und diese veraendern zu koennen, nennt man …', 
'EPL.', 
'SQL.', 
'RDF.', 
'OWL.', 
2, 1),

('Einfuehrung in das Internet of Things', 'Aus wie vielen Komponenten besteht das Smart Energy Konzept?', 
'4', 
'3', 
'2', 
'5', 
1, 1),

('Einfuehrung in das Internet of Things', 'ueber welche Protokolle kommunizieren Gateways mit Zentralsystemen in IoT-Plattformen haeufig?', 
'HTTP oder MQTT', 
'HTTP oder HTML', 
'HTTP oder MSMQ', 
'HTTP oder TCP/IP', 
1, 1),

('Einfuehrung in das Internet of Things', 'Fachkraeftemangel und demographischer Wandel gefaehrden das …', 
'Fachkraeftepotential.', 
'Arbeitskraeftepotential.', 
'Entwicklungspotential.', 
'Innovationspotential.', 
4, 1),

('Einfuehrung in das Internet of Things', 'Ziel des Web 3.0 ist es, Computern die Interpretation und Einordnung von …', 
'Informationen zu ermoeglichen.', 
'Webseiten zu ermoeglichen.', 
'Metatexten und Webseiten zu ermoeglichen.', 
'Semantischen Datenbanken zu ermoeglichen.', 
1, 1),

('Einfuehrung in das Internet of Things', 'Aus was besteht eine Drei-Schichten-Architektur typischerweise?', 
'GUI-Schicht, Middleware, Datenhaltungsschicht', 
'GUI-Schicht, Fachkonzeptschicht, Datenhaltungsschicht', 
'Fachkonzeptschicht, Datenbankschicht, Datenhaltungsschicht', 
'Applikation, Middleware, Betriebssystem', 
2, 1),

-- Fragen aus "Ergonomie fuer die Web-Entwicklung"
('Ergonomie fuer die Web-Entwicklung', 'Was bezeichnet der Begriff „User Interface“?', 
'Die Schnittstellen zwischen dem Menschen und einem Produkt', 
'Die Leistungsmoeglichkeiten eines Produkts', 
'Die Gebrauchstauglichkeit einer Benutzeroberflaeche', 
'Die Anpassung zwischen dem Menschen und seinen Arbeitsbedingungen', 
1, 1),

('Ergonomie fuer die Web-Entwicklung', 'Als was wird das Layout Pattern Tiny Tweaks auch bezeichnet?', 
'Mobile Only', 
'Mobile First', 
'Mostly Mobile', 
'Mobile Best', 
1, 1),

('Ergonomie fuer die Web-Entwicklung', 'Welche Herangehensweise bei der Gestaltung einer Website entspricht nicht der Grundidee des Responsive Design?', 
'Die Gestaltung fuer veraenderliche Fenstergroeßen', 
'Die Gestaltung des Weblayouts fuer fixe Fenstergroeßen', 
'Die Anpassung auf unterschiedliche Ausgabegeraete', 
'Die Anpassung von Inhalten fuer die mobile Ausgabe', 
2, 1),

('Ergonomie fuer die Web-Entwicklung', 'Welches Website-Suchverhalten ist charakteristisch fuer eine ergebnisorientierte Vorgehensweise und eine klare Vorstellung des Ziels?', 
'Kein Suchverhalten wird so charakterisiert.', 
'Das Verhalten des Researchers', 
'Das Verhalten des Browsers', 
'Das Verhalten des Suchers', 
4, 1),

('Ergonomie fuer die Web-Entwicklung', 'Wie werden Spalteninhalte des Layoutpatterns Column Drop bei Veraenderung der Bildschirmbreite angepasst?', 
'Die Spaltenbreite passt sich fluide der Breite an, bei Verkleinerung des Bildschirms werden Spalteninhalte neu angeordnet.', 
'Die Spaltenbreite bleibt weitgehend konstant, bei einer Verkleinerung des Bildschirms werden Spalten abgesenkt.', 
'Das genannte Layoutpattern ist einspaltig, bei Veraenderung der Bildschirmbreite wird der gesamte Inhalt fluide angepasst.', 
'Die Spaltenbreite bleibt fest, bei Verkleinerung des Bildschirms werden Spalten erst ab einer minimalen Breite abgesenkt.', 
2, 1),

('Ergonomie fuer die Web-Entwicklung', 'Wodurch zeichnet sich ein CLI aus?', 
'Der Benutzer kann die Interaktion ohne zusaetzliche Eingabegeraete durchfuehren.', 
'Der Benutzer kann die Interaktion ohne Blickzuwendung oder motorische Eingabe durchfuehren.', 
'Der Benutzer kann die Interaktion ohne Positionierungseingaben durchfuehren.', 
'Der Benutzer kann die Interaktion ohne vorherige Kenntnis der Befehle durchfuehren.', 
3, 1),

('Ergonomie fuer die Web-Entwicklung', 'In welchem Verhaeltnis stehen Ergonomie und Usability zueinander?', 
'Ergonomie bezieht sich auf Anwendungen im Unterhaltungsbereich, Usability auf Anwendungen im Arbeitsumfeld.', 
'Usability ist ein Teilbereich von Ergonomie und bezieht sich auf die bedienfreundliche Gestaltung von Interfaces.', 
'Ergonomie ist ein Teilbereich von Usability und bezieht sich auf die funktionale Gestaltung von Interfaces.', 
'Ergonomie bezieht sich auf Anwendungen im Arbeitsumfeld, Usability auf Anwendungen im Bereich Unterhaltung.', 
2, 1);
